#!/usr/bin/env bash

targetdir='/c/Program Files/sh.net'

# Install sinister
curl -sSLo /tmp/sinister http://git.io/sinister
chmod a+rx /tmp/sinister

root=$(dirname "$0")
cd "$root"

for script in scripts/*
do
    name=$(basename "$script")
    cat "$script" | /tmp/sinister -o "$targetdir" -n "$name"
done
