#!/usr/bin/env bash

targetdir=~/AppData/Local/sh.net

# Cleanup from previous installs
rm -rf "$targetdir"
mkdir -p "$targetdir"

for script in scripts/*
do
    name=$(basename "$script")
    dest="$targetdir/$name"
    
    # Do the work
    cat "$script" | tee "$dest" 1> /dev/null # use tee to handle null chars
    chmod a+rx "$dest" # modify permissions
done
