#!/usr/bin/env bash

get_path()
{
    powershell "[Environment]::GetEnvironmentVariable('PATH', 'User')"
}

set_path()
{
    powershell "[Environment]::SetEnvironmentVariable('PATH', '$1', 'User')"
}

wpwd()
{
    powershell 'Write-Host -NoNewline $pwd'
}

targetdir=~/AppData/Local/sh.net

# Cleanup from previous installs
rm -rf "$targetdir"
mkdir -p "$targetdir"

cp -r scripts "$targetdir" # copy the scripts recursively
find "$targetdir" -type f -exec chmod a+rx {} \; # modify permissions

# Add the dir to $PATH
if ! type devenv &>/dev/null; then
    current_path=$(get_path)
    to_append=$(cd "$targetdir" && wpwd)
    set_path "$current_path;$to_append"
fi
